"""Define Pydantic models for API JSON request and response bodies.

FastAPI parses and validates JSON bodies using request models, and validates
and serializes output using response_model. Field descriptions also appear in
the generated API documentation. knowledge_base_id is a UUID string generated
by KnowledgeBaseRegistry, not a topic or filename. These models retain str
typing without validating UUID syntax; the registry checks whether an ID exists.

"""

from pydantic import BaseModel, Field


class TextIngestRequest(BaseModel):
    """
        Text ingestion parameters; source_name labels the source in retrieval results.
    """

    text: str = Field(min_length=1, description="Source text to ingest, with at least one character.")
    source_name: str = Field(default="pasted-text", description="Name identifying the source text.")
    knowledge_base_id: str | None = Field(
        default=None,
        description="Existing knowledge base ID to extend; omit or use null to create one.",
    )


class IngestResponse(BaseModel):
    """
        Return the knowledge base ID and source label for this ingestion request.
    """

    knowledge_base_id: str = Field(description="ID to reuse when adding sources or asking questions.")
    source: str = Field(description="Source name, filename, or video URL for this ingestion request.")


class QuestionRequest(BaseModel):
    """
        Ask within one knowledge base without searching other knowledge bases.

        min_length counts characters; it does not trim or reject whitespace-only strings.
    """

    knowledge_base_id: str = Field(description="Existing knowledge base ID returned by ingestion.")
    question: str = Field(min_length=1, description="Question text with at least one character.")
    k: int | None = Field(
        default=None,
        ge=1,
        le=20,
        description="Maximum chunks to retrieve; omit or use null for the service default.",
    )


class SourceItem(BaseModel):
    """
        One retrieved chunk; validates data format, not source credibility.
    """

    source: str = Field(description="Chunk source label; unknown when source metadata is missing.")
    page: int | None = Field(
        default=None,
        description="Page index from the loader, unchanged without adding one; null when unavailable.",
    )
    content: str = Field(description="Retrieved chunk text, not the full source document.")


class AnswerResponse(BaseModel):
    """
        Generated answer and retrieved context; does not imply sentence-level citation verification.
    """

    answer: str = Field(description="Answer generated by the model from retrieved context.")
    sources: list[SourceItem] = Field(description="Source chunks retrieved for this request.")
